#!/usr/bin/env node
import { execSync } from 'child_process'
import path from 'path'

console.log('✅ Running core installation...')

const installHooksPath = path.resolve('./hooks/install-hooks.js')
execSync(`node ${installHooksPath}`, { stdio: 'inherit' })

const installCommandsPath = path.resolve('./commands/install-commands.js')
execSync(`node ${installCommandsPath}`, { stdio: 'inherit' })

console.log('✅ Core installation complete')
