#!/usr/bin/env bash
set -euo pipefail

HOME_DIR=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)
export HOME_DIR
. "$HOME_DIR/core/scripts/logger.sh"

info "running system setup ..."
"$HOME_DIR/core/setup/dev/setup"

node "$HOME_DIR/core/hooks/install-hooks.js"
node "$HOME_DIR/core/commands/install-commands.js"

success "core installation complete"
