#!/usr/bin/env bash
set -euo pipefail

. ./setup/dev/common

info "running system setup ..."
./setup/dev/setup

node ./hooks/install-hooks.js
node ./commands/install-commands.js

success "core installation complete"
