#!/usr/bin/env bash
set -euo pipefail

homeDir=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)
setupDev="$homeDir/core/setupDev"
scripts="$homeDir/core/scripts"

export homeDir
export setupDev
export scripts

. "$scripts/logger.sh"

info "running system setup ..."
$setupDev/setup

node "$homeDir/core/hooks/install-hooks.js"
node "$homeDir/core/commands/install-commands.js"

success "core installation complete"
