#!/usr/bin/env bash
set -euo pipefail

$setupDev/node
# bash "$(dirname "$0")/npmPackages"
sudo homeDir="$homeDir" node "$homeDir/core/setup/dev/nginx"
# bash "$(dirname "$0")/adsPower"
# bash "$(dirname "$0")/astrill"
