#!/usr/bin/env node

import {
    divide,
    info,
    success,
} from '../../scripts/logger.js'
import {
    startTimer,
    stopTimer,
} from '../../scripts/timer.js'
import run from './run'

startTimer('dropAll')

divide()
info('Dropping all databases ...')
divide()

const params = {
    app: 'query',
    command: 'dropParts',
}

await run(params)

divide()
success('Dropped all databases')
divide()

stopTimer('dropAll')
