#!/usr/bin/env node

import { errorAndExit } from '../../scripts/logger.js'
import run from './run'

const part = process.argv[2]

if (!part) {
    errorAndExit('Usage: drop <database>')
}

await run({
    app: 'query',
    command: 'drop',
    part,
    show: true,
})
