#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import {
    startTimer,
    stopTimer
} from '../../scripts/timer.js'
import {
    divide,
    info,
    warning,
} from '../../scripts/logger.js'
import { runOnTerminal } from '../../scripts/terminal.js'
import {
    getFileLines,
    isDir,
    isFile,
} from "../../scripts/os.js"
import extract from "../../scripts/extract.js"
import run from "./run"

const args = process.argv.slice(2)
let name = args[0] || ''
const params = extract()

startTimer()

if (!name) {
    runOnTerminal('dropAll')

    const {
        process: proc,
        repo,
        apiRepository,
    } = process.env

    const dependenciesPath = `${repo}/common/dependencies`
    const orderFile = '/generation/order'
    const orderList = getFileLines(orderFile)
    const depsList = getFileLines(dependenciesPath)

    const set = new Set(depsList)

    const first = orderList.filter(x => set.has(x))
    const second = depsList.filter(x => !orderList.includes(x))
    const finalList = [...first, ...second]

    for (const dependency of finalList) {
        let orgOrRepo
        if (isDir(`/${apiRepository}/${dependency}`)) {
            orgOrRepo = apiRepository
        } else {
            orgOrRepo = 'gesht'
        }

        const base = `/${orgOrRepo}/${dependency}`
        const partFile = `${base}/part`

        if (!isFile(partFile)) {
            warning(`Did not find part file for ${orgOrRepo}/${dependency}`)
            continue
        }

        process.chdir(base)
        runOnTerminal('generate')
    }

    runOnTerminal('insertData')
    stopTimer()
    process.exit(0)
}

name = name.replace('/', '')

const command = `
        find /spl \
            -maxdepth 1 -mindepth 1 -type d \
            -not -name "core" \
            -name '*${name}*' 2>/dev/null
    `
const result = runOnTerminal(command)
const dirs = result.split('\n').filter(Boolean)

for (const dir of dirs) {
    const partFile = path.join(dir, 'part')
    if (isFile(partFile)) {
        process.chdir(dir)
        runOnTerminal(`generate`)
    }
}

const pwd = process.cwd()
const partFile = path.join(pwd, 'part')

if (!isFile(partFile)) {
    warning(`Did not find ${pwd}/part`)
    stopTimer()
    process.exit(0)
}

run(params)

stopTimer()
