#!/usr/bin/env node

import path from 'path'
import {
    startTimer,
    stopTimer
} from '../../scripts/timer.js'
import {
    divide,
    errorAndExit,
    info,
    warning,
} from '../../scripts/logger.js'
import { runOnTerminal } from '../../scripts/terminal.js'
import {
    getFileLines,
    isDir,
    isFile,
} from "../../scripts/os.js"
import extract from "../../scripts/extract.js"
import run from "./run"

const args = process.argv.slice(2)
let search = args[0] || ''

startTimer()

if (!search) {
    runOnTerminal('dropAll', { show: true })

    const {
        process: proc,
        repo,
        apiRepository,
    } = process.env

    const essentialPartsPath = `/core/essentialParts`
    const partsPath = `/${repo}/common/dependencies`
    const orderFile = '/generation/order'
    const orderList = getFileLines(orderFile)
    const essentialParts = getFileLines(essentialPartsPath)
    const parts = getFileLines(partsPath)

    const set = new Set([...essentialParts, ...parts])

    const first = orderList.filter(x => set.has(x))
    const second = parts.filter(x => !orderList.includes(x))
    const finalList = [...first, ...second]

    for (const part of finalList) {
        let orgOrRepo
        if (isDir(`/${apiRepository}/${part}`)) {
            orgOrRepo = apiRepository
        } else {
            orgOrRepo = 'holizm'
        }

        const base = `/${part}`
        const partFile = `${base}/part`

        if (!isFile(partFile)) {
            warning(`Did not find part file for ${partFile}`)
            continue
        }

        process.chdir(base)
        runOnTerminal(`generate ${part}`, { show: true })
    }

    // runOnTerminal('insertData', { show: true })
    stopTimer()
    process.exit(0)
}

search = search.replace('/', '')

const command = `
    find / \
        -maxdepth 1 -mindepth 1 -type d \
        -name '*${search}*' \
        -exec test -f "{}/part" \\; \
        -print 2>/dev/null
`
const result = runOnTerminal(command)
const dirs = result.split('\n').filter(Boolean)
if (dirs.length > 1) {
    for (const dir of dirs) {
        const partFile = `${dir}/part`
        if (isFile(partFile)) {
            process.chdir(dir)
            runOnTerminal(`generate ${dir}`, { show: true })
        }
    }
    stopTimer()
    process.exit(0)
}

if (dirs.length === 0) {
    errorAndExit(`No part is found for search ${search}`)
}

process.chdir(dirs[0])
divide()
const params = extract({
    container: true,
})
divide()
const partFile = `/${params.repo}/part`

if (!isFile(partFile)) {
    warning(`Did not find ${partFile}`)
    stopTimer()
    process.exit(0)
}

run({
    app: 'generation',
    part: params.repo,
    partPath: `/${params.repo}`,
    show: true,
})

stopTimer()
