#!/usr/bin/env node

import {
    divide,
    info,
} from '../../scripts/logger.js'
import { getFileLines, isDir } from "../../scripts/os.js"
import { runOnTerminal } from '../../scripts/terminal.js'
import {
    startTimer,
    stopTimer
} from '../../scripts/timer.js'

const {
    process: proc,
    repo,
} = process.env

runOnTerminal('dropAll')

startTimer('generateAll')
const dependenciesPath = `${repo}/common/dependencies`
const orderFile = '/generation/order'
const orderList = getFileLines(orderFile)
const depsList = getFileLines(dependenciesPath)

const set = new Set(depsList)

const first = orderList.filter(x => set.has(x))
const second = depsList.filter(x => !orderList.includes(x))
const finalList = [...first, ...second]

for (const dependency of finalList) {
    let orgOrRepo
    if (isDir(`/${apiRepository}/${dependency}`)) {
        orgOrRepo = apiRepository
    } else {
        orgOrRepo = 'gesht'
    }

    const base = `/${orgOrRepo}/${dependency}`
    const part = `${base}/part`

    if (!isFile(part)) {
        warning(`Did not find part file for ${orgOrRepo}/${dependency}`)
        continue
    }

    process.chdir(base)
    runOnTerminal('generate')
}

runOnTerminal('insertData')

stopTimer('generateAll')
