#!/usr/bin/env bash

. /core/scripts/initializeApiBarrels.sh

if [[ ! -d /$repo/$process/node_modules ]] || [[ ! -f /$repo/$process/package-lock.json ]]; then
    cd /$repo/$process
    npm install --legacy-peer-deps
fi
