#!/usr/bin/env node

import { isFile } from "../../scripts/os.js"
import {
    clear,
    runOnTerminal,
} from '../../scripts/terminal.js'
import run from './run'

const repo = process.env.apiRepository

clear()

const findCmd = `find / -type f -path "*/api/data/*" -not -path '*/node_modules/*' -name "*.json" -printf "%p\n" 2>/dev/null`
let files = runOnTerminal(findCmd).split('\n')

let initialFile = `/${repo}/common/initial.js`
if (isFile(initialFile)) files.push(initialFile)

run({
    command: 'insertFiles',
    files,
})
