#!/usr/bin/env node

import { isFile } from "../../scripts/os.js"
import {
    clear,
    runOnTerminal,
} from '../../scripts/terminal.js'
import run from './run'

const repo = process.env.apiRepo

clear()

const findCmd = `find / -type f -path "*/api/data/*" -not -path '*/node_modules/*' -name "*.json" -printf "%p\n" 2>/dev/null`
let files = runOnTerminal(findCmd).split('\n')

let initialFile = `${home}/${repo}/common/initial.js`
if (isFile(initialFile)) files.push(initialFile)
run({
    app: 'query',
    command: 'insertData',
    files,
    show: true,
})
