#!/usr/bin/env bash

processHome=$home/$repo/$process
repoHome=$home/$repo
packageHash=$(sha256sum $repoHome/package.json $processHome/package-lock.json | sha256sum | cut -d ' ' -f 1)
packageHashFile=$repoHome/node_modules/.packageHash
packageLockFile=$repoHome/node_modules/.packageLock

exec 9>$packageLockFile
flock 9

if [[ ! -f $packageHashFile ]] || [[ $(<$packageHashFile) != $packageHash ]]; then
    cp $processHome/package-lock.json $repoHome/package-lock.json
    cd $repoHome
    npm install --legacy-peer-deps
    cp $repoHome/package-lock.json $processHome/package-lock.json
    packageHash=$(sha256sum $repoHome/package.json $processHome/package-lock.json | sha256sum | cut -d ' ' -f 1)
    echo $packageHash > $packageHashFile
fi

find $processHome/node_modules -maxdepth 1 -type d -name ".*" -exec rm -rf {} +
