#!/usr/bin/env bash

if [[ ! -d $home/$repo/$process/node_modules ]] || [[ ! -f $home/$repo/$process/package-lock.json ]]; then
    cd $home/$repo/$process
    npm install --legacy-peer-deps
fi
find node_modules -maxdepth 1 -type d -name ".*" -exec rm -rf {} +
