#!/usr/bin/env node

import { clear } from '../../scripts/terminal.js'
import run from './run'

clear()

await run({
    app: 'migration',
    command: 'newEnumItems',
    part: process.argv[0],
    show: true,
    type: process.argv[1],
})
