#!/usr/bin/env node

import {
    clear,
    runStreaming,
} from '../../scripts/terminal.js'
import findDifferentParts from './findDifferentParts.js'
import migratePart from './migratePart.js'
import migrateParts from './migrateParts.js'
import run from './run'

const { apiRepo } = process.env
const search = process.argv[2] || ''
const developmentPath = `/tmp/${apiRepo}/migration/development`
const productionPath = `/tmp/${apiRepo}/migration/production`

clear()
await runStreaming(['compare', search].filter(Boolean).join(' '))
await run({
    app: 'migration',
    command: 'adHoc',
    part: search,
    show: true,
})

const parts = findDifferentParts(developmentPath, productionPath, search)
await migrateParts(parts, migratePart)
