#!/usr/bin/env node

import { isFile } from "../../scripts/os.js"
import {
    clear,
    runOnTerminal,
} from '../../scripts/terminal.js'
import run from './run'

const {
    apiRepo,
    home,
} = process.env

clear()

await run({
    app: 'migration',
    command: 'newEnumItems',
    show: true,
})
