#!/usr/bin/env bash

inotifywait -m -r \
-e modify \
-e move \
-e create \
-e delete \
--exclude "exports.js" \
-q \
$directories |
while IFS=' ' read directory event file
do
    export directory
    export event
    export file
    echo $directory $file $event
    topLevelDir=$(echo $directory | cut -d'/' -f1)
    node /core/commands/api/generateExports.js $topLevelDir
done
