#!/usr/bin/env bash

directories=$(find /spl -maxdepth 1 -mindepth 1 -type d | sed 's|/spl/||' | sort)
echo $directories

node /core/commands/api/generateExports.js $directories
node /core/commands/api/generatePackageJsonFiles.js $directories
echo "done"

inotifywait -m -r \
-e modify \
-e move \
-e create \
-e delete \
--exclude "exports.js" \
-q \
$directories |
while IFS=' ' read directory event file
do
    export directory
    export event
    export file
    echo $directory $file $event
    node /core/commands/api/generateExports.js $directory
done
