#!/usr/bin/env bash
exit

echo "Linking: $1"
export targetProject=$1
export targetPath=~/$1

ln -s -f /api/package.json $targetPath
ln -s -f /api/package-lock.json $targetPath
ln -s -f /api/core $targetPath
ln -s -f /api/process.js $targetPath
ln -s -f /npm/node_modules $targetPath

files=(
    "privateSettings.json"
    "publicSettings.json"
    "settingsOverride.json"
    "common.json"
    "repo.json"
    "instance.json"
    "connectionStrings.json"
)

for file in "${files[@]}"; do
    if [ -f /$apiRepo/$apiProcess/$file ]; then
        cp /$apiRepo/$apiProcess/$file $targetPath
    fi
done

find \
    / \
    /$repo/$process \
    -type f \
    -name part \
    -not -path '*/migration/*' \
    -not -path '*/query/*' \
    -not -path '*/generation/*' \
    | \
while read part;
do
    partName=$(basename $(dirname $part))
    mkdir -p /$targetProject/$partName
    cp $part /$targetProject/$partName
done

cp -r /$apiRepo/$apiProcess/.vscode $targetPath
sed -i "s/$apiRepo//g" $targetPath/.vscode/launch.json
sed -i "s/$apiProcess/$targetProject/g" $targetPath/.vscode/launch.json
