#!/usr/bin/env node

import { runOnTerminal } from '../../scripts/terminal.js'

const run = (...args) => {
    const cmd = `node --preserve-symlinks /query/process.js ${args.map(a => `'${a}'`).join(' ')}`
    runOnTerminal(cmd)
}

process.chdir('/HolismHolding/Query')
run(...process.argv.slice(2))
