#!/usr/bin/env bash

echo "Linking: $1"
export targetProject=$1
export targetPath=/$1

ln -s -f /$apiRepo/$apiProcess/package.json $targetPath
ln -s -f /$apiRepo/$apiProcess/package-lock.json $targetPath
ln -s -f /$apiRepo/$apiProcess/node_modules $targetPath

files=(
    "common.json"
    "connectionStrings.json"
    "instance.json"
    "privateSettings.json"
    "publicSettings.json"
    "repo.json"
    "settingsOverride.json"
)

for file in "${files[@]}"; do
    if [ -f /$apiRepo/$apiProcess/$file ]; then
        cp /$apiRepo/$apiProcess/$file $targetPath
    fi
done

find /spl \
    -maxdepth 1 \
    -mindepth 1 \
    -type d \
    | \
while read part;
do
    partName=$(basename $part)
    # mkdir -p /$targetProject/$partName
    # cp $part /$targetProject/$partName
done

cp -r /$apiRepo/$apiProcess/.vscode $targetPath
sed -i "s/$apiRepo//g" $targetPath/.vscode/launch.json
sed -i "s/$apiProcess/$targetProject/g" $targetPath/.vscode/launch.json
