#!/usr/bin/env bash

if [[ $apiProcess != admin* ]]; then
    exit 0
fi

echo "Linking: $1"
export targetProject=$1
export targetPath=$home/$1

ln -s -f $home/$apiRepo/package.json $targetPath
ln -s -f $home/$apiRepo/package-lock.json $targetPath

rm -rf $targetPath/node_modules
mkdir -p $targetPath/node_modules

shopt -s dotglob
for sourcePath in $home/$apiRepo/$apiProcess/node_modules/*; do
    if [[ -e $sourcePath ]]; then
        ln -s -f -n $sourcePath $targetPath/node_modules/$(basename $sourcePath)
    fi
done

files=(
    "common.json"
    "connectionStrings.json"
    "instance.json"
    "privateSettings.json"
    "publicSettings.json"
    "repo.json"
    "settingsOverride.json"
)

for file in "${files[@]}"; do
    if [ -f $home/$apiRepo/$apiProcess/$file ]; then
        ln -s -f $home/$apiRepo/$apiProcess/$file $targetPath/$file
    fi
done

find $home/spl \
    -maxdepth 1 \
    -mindepth 1 \
    -type d \
    | \
while read part;
do
    partName=$(basename $part)
    # mkdir -p /$targetProject/$partName
    # cp $part /$targetProject/$partName
done

cp -r $home/$apiRepo/$apiProcess/.vscode $targetPath
sed -i "s/$apiRepo//g" $targetPath/.vscode/launch.json
sed -i "s/$apiProcess/$targetProject/g" $targetPath/.vscode/launch.json
