#!/usr/bin/env node

import { runOnTerminal } from '../../scripts/terminal.js'

export default (...args) => {
    const cmd = `node --preserve-symlinks /query/process.js ${args.map(a => `'${a}'`).join(' ')}`
    runOnTerminal(cmd)
}
