#!/usr/bin/env node

import {
    runOnTerminal,
} from '../../scripts/terminal.js'

export default params => {
    const {
        app,
        ...rest
    } = params
    const args = Object.entries(rest)
        .map(([k, v]) => `${k}=${v}`)
        .join(' ')
    const cmd = `node --preserve-symlinks /${app}/process.js ${args}`
    runOnTerminal(cmd, params)
}
