#!/usr/bin/env node

import {
    divide,
    info,
} from '../../scripts/logger.js'
import {
    runOnTerminal,
    runStreaming,
} from '../../scripts/terminal.js'

const {
    home,
    isEtl,
    process: proc,
    repo,
} = process.env

const main = async () => {
    divide()
    info('Starting...')
    process.chdir(`${home}/${repo}/${proc}`)
    divide()
    if (isEtl === 'true') {
        info('ETL')
        return
    }
    runOnTerminal('nohup monitor >/tmp/apiMonitor.log 2>&1 &', {
        throwOnError: true,
    })
    const command = `nodemon --watch ${home} --ignore "**/*.json" process.js`
    console.log(command)
    await runStreaming(command)
}

main().catch(e => {
    info(String(e))
})
