#!/usr/bin/env node

import {
    divide,
    info,
} from '../../scripts/logger.js'
import { isFile } from '../../scripts/os.js'
import {
    clear,
    runOnTerminal,
    runStreaming,
} from '../../scripts/terminal.js'

const {
    process: proc,
    repo,
} = process.env

console.log('hi')

clear()
runOnTerminal('stop')

divide()
if (isFile('package.json')) {
    info('Stopping...')
} else {
    info(`Stopping /${repo}/${proc} ...`)
}
divide()

// await runStreaming(`pkill -f "nodemon --watch /${repo}"`)
