#!/usr/bin/env bash

exit

directories=$(find -L /$apiRepo/$apiProcess/node_modules -maxdepth 1 -mindepth 1 -type d -name '[A-Z]*')

node /core/commands/api/generateExports.mjs $directories
node /core/commands/api/generatePackageJsonFiles.mjs $directories

inotifywait -m -r \
-e modify \
-e move \
-e create \
-e delete \
--exclude "exports.js" \
-q \
$directories |
while IFS=' ' read directory event file
do
    export directory
    export event
    export file
    echo $directory $file $event
    node /core/commands/api/generateExports.mjs $directory
done
