#!/usr/bin/env bash

. $HOME/core/scripts/logger.sh

if [[ $# -eq 0 ]]; then
    errorAndExit "Usage: copyId domain"
fi

domain=$1

read -r sshPort sshUser sshIp < <(node ~/core/scripts/extractSshParameters.js "$domain")

if [[ -z "$sshPort" || -z "$sshUser" || -z "$sshIp" ]]; then
    errorAndExit "Failed to extract SSH parameters for $domain"
fi

ssh-copy-id -p "$sshPort" "$sshUser@$sshIp"
