#!/usr/bin/env node

import {
    divide,
    info,
    warning,
} from '../scripts/logger.js'
import {
    isApi,
    isHeadlessPanel,
    isPanel,
    isSite,
    isWorker,
    removeAndRecreateDir,
} from '../scripts/os.js'
import {
    clear,
    runStreaming,
} from '../scripts/terminal.js'
import getPaths from '../scripts/getPaths.js'
import ensureDependencies from '../scripts/ensureDependencies.js'
import buildApi from '../scripts/buildApi.js'
import buildPanel from '../scripts/buildPanel.js'
import buildSite from '../scripts/buildSite.js'
import extract from '../scripts/extract.js'

clear()

divide()
info('holism build')
divide()
info(`directory: ${process.cwd()}`)
divide()

let params = extract()

params = {
    ...params,
    ...getPaths(params),
}

ensureDependencies(params)
params.containerFile = `${params.buildPath}/container`
params.imageName = `ghcr.io/${params.lowercaseOrg}/${params.lowercaseRepo}/${params.lowercaseProcess}:latest`

divide()
removeAndRecreateDir(params.buildPath)

if (isApi(params)) {
    buildApi(params)
} else if (isPanel(params)) {
    if (isHeadlessPanel(params)) {
        buildHeadlessPanel(params)
    } else {
        buildPanel(params)
    }
} else if (isSite(params)) {
    buildSite(params)
} else if (isWorker(params)) {
    buildApi(params)
} else {
    warning('Unknown process')
}

let cmd = `docker --debug build \
-f ${params.containerFile} \
-t ${params.imageName} \
/tmp/build --no-cache --progress=plain`
runStreaming(cmd)
