#!/usr/bin/env node
import fs from 'fs'
import path from 'path'
import { error, info } from '../scripts/logger.js'
import camelize from '../scripts/camelize.js'
import { runOnTerminal } from '../scripts/terminal.js'

const list = runOnTerminal("find . -name .git -prune -o -print")
    .split('\n')
    .filter(Boolean)
    .sort((a, b) => b.split('/').length - a.split('/').length)

for (const p of list) {
    try {
        if (p === '.') continue

        const stat = fs.lstatSync(p)

        const segments = p.split('/').filter(s => s && s !== '.')

        const newSegments = segments.map((seg, i) => {
            const isLast = i === segments.length - 1

            if (isLast && !stat.isDirectory()) {
                const { name: stem, ext } = path.parse(seg)
                return camelize(stem) + ext
            }
            return camelize(seg)
        })

        const newPath = './' + newSegments.join('/')

        if (newPath !== p) {
            fs.renameSync(p, newPath)
        }
    } catch (e) {
        // error(e)
    }
}
