#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import { runOnTerminal } from '../scripts/terminal.js'
import camelize from '../scripts/camelize.js'

const list = runOnTerminal('find . -name .git -prune -o -print')
    .split('\n')
    .filter(Boolean)
    .sort((a, b) => b.split('/').length - a.split('/').length)

for (const oldPath of list) {
    if (oldPath === '.') continue

    try {
        const stat = fs.lstatSync(oldPath)

        const dir = path.dirname(oldPath)
        const base = path.basename(oldPath)

        let newBase

        if (stat.isDirectory()) {
            newBase = camelize(base)
        } else {
            const { name, ext } = path.parse(base)
            newBase = camelize(name) + ext
        }

        if (newBase !== base) {
            fs.renameSync(oldPath, path.join(dir, newBase))
        }
    } catch { }
}
