#!/usr/bin/env node
import fs from 'fs'
import path from 'path'
import { error, info } from '../scripts/logger.js'
import camelize from '../scripts/camelize.js'
import { runOnTerminal } from '../scripts/terminal.js'

const list = runOnTerminal("find . -name .git -prune -o -print")
    .split('\n')
    .filter(Boolean)
    .sort((a, b) => b.split('/').length - a.split('/').length)

for (const p of list) {
    try {
        const dir = path.dirname(p)
        const base = path.basename(p)
        const stat = fs.lstatSync(p)

        const { name: stem, ext } = stat.isDirectory()
            ? { name: base, ext: '' }
            : path.parse(base)

        const newStem = camelize(stem)
        const newName = newStem + ext

        if (newName !== base) {
            const newPath = path.join(dir, newName)
            fs.renameSync(p, newPath)
        }
    } catch (e) {
        error(e)
    }
}
