#!/usr/bin/env node

import dnsProviders from '../scripts/dnsProviders.js'
import { runOnTerminal } from '../scripts/terminal.js'
import { info, error, success } from '../scripts/logger.js'

const getCurrentDns = () => {
    const dnsResolver = runOnTerminal(
        `lsof -i :53 | awk 'NR>1 {print $1}' | uniq`
    )

    return dnsResolver === 'dnsmasq'
        ? runOnTerminal(
            `grep '^server=' /etc/dnsmasq.conf | awk -F '=' '{print $2}' | tr '\\n' ' '`
        )
        : runOnTerminal(
            `grep '^nameserver' /run/systemd/resolve/resolv.conf | awk '{print $2}' | tr '\\n' ' '`
        )
}

const flushDnsCache = () => {
    if (runOnTerminal(`systemctl is-active systemd-resolved`, { hideErrors: true })) {
        runOnTerminal(`sudo systemd-resolve --flush-caches`, { hideErrors: true })
    } else if (runOnTerminal(`command -v resolvectl`, { hideErrors: true })) {
        runOnTerminal(`sudo resolvectl flush-caches`, { hideErrors: true })
    }
}

const applyDns = key => {
    if (!dnsProviders[key]) {
        error(`DNS key '${key}' not found!`)
        info('Keys are:')
        Object.keys(dnsProviders).forEach(k => info(` ${k}`))
        process.exit(1)
    }

    const [name, ips] = dnsProviders[key].split('|')
    info(`Applying DNS configuration: ${name} (${ips})`)

    const dnsResolver = runOnTerminal(
        `lsof -i :53 | awk 'NR>1 {print $1}' | uniq`
    )

    if (dnsResolver === 'dnsmasq') {
        const currentConfig = runOnTerminal(
            `grep '^server=' /etc/dnsmasq.conf | awk -F '=' '{print $2}' | tr '\\n' ' '`
        )

        if (currentConfig !== ips) {
            runOnTerminal(`sudo sed -i "/^server=/d" /etc/dnsmasq.conf`)
            ips.split(' ').forEach(ip => {
                runOnTerminal(`echo "server=${ip}" | sudo tee -a /etc/dnsmasq.conf > /dev/null`)
            })
            runOnTerminal(`sudo systemctl restart dnsmasq`)
        }
    } else {
        const connections = runOnTerminal(
            `nmcli --terse --fields NAME connection show --active | grep -vE '^\\s*$'`
        )
            .split('\n')
            .filter(Boolean)

        connections.forEach(connection => {
            runOnTerminal(`nmcli connection modify "${connection}" ipv4.dns "${ips}"`)
            runOnTerminal(`nmcli connection modify "${connection}" ipv4.ignore-auto-dns yes`)
            runOnTerminal(`nmcli connection down "${connection}"`)
            runOnTerminal(`nmcli connection up "${connection}"`)
        })
    }

    flushDnsCache()
    success(`DNS servers updated to ${name} (${ips}).`)
}

const nextDnsKey = currentKey => {
    const keys = Object.keys(dnsProviders)
    const index = keys.indexOf(currentKey)
    return index === -1 ? null : keys[(index + 1) % keys.length]
}

const switchDns = () => {
    const currentDns = getCurrentDns()
    let newDnsKey = ''

    Object.entries(dnsProviders).some(([key, value]) => {
        const [, ips] = value.split('|')
        const firstIp = ips.split(' ')[0]
        if (currentDns.includes(firstIp)) {
            newDnsKey = nextDnsKey(key)
            return true
        }
        return false
    })

    applyDns(newDnsKey || 'cloudflare')
}

const args = process.argv.slice(2)

if (args.length === 0) {
    switchDns()
} else {
    applyDns(args[0])
}
