#!/usr/bin/env bash

. $HOME/core/scripts/logger.sh

target=$1
home=$HOME

if [[ $target == "" ]]; then
    target=$PWD
fi

if [[ $target == / ]]; then
    error 'Checking the root is not possible'
    exit
fi

divide
info "Checking $target ..."
divide

if [[ $target = /* ]]; then
    target=$target
elif [[ $target = ./* ]]; then
    target=$PWD/${target/.\//}
else
    target=$PWD/$target
fi

node "$home/core/scripts/checkFiles.js" "$target"

# findRepos $target |
# while read repo;
# do
#     node $home/policies/git/run.js $repo
# done

divide
