#!/usr/bin/env node

import { clear } from '../scripts/terminal.js'
import {
    divide,
    info,
} from '../scripts/logger.js'
import build from '../scripts/build.js'

clear()

divide()
info('holism deploy')
divide()

const params = await build({
    isCiCd: false,
    localBuild: true,
})

console.log(params)
