#!/usr/bin/env node

import {
    clear,
    runOnTerminal,
    runStreaming,
} from '../scripts/terminal.js'
import {
    divide,
    errorAndExit,
    info,
} from '../scripts/logger.js'
import build from '../scripts/build.js'
import runOnServer from '../scripts/runOnServer.js'

const domain = process.argv[2]
if (!domain) {
    errorAndExit('Domain is not provided')
}

clear()

divide()
info('holism deploy')
divide()

const params = await build({
    isCiCd: false,
    localBuild: true,
})

const {
    processBuildDir,
    repo,
} = params

await runOnServer(domain, `mkdir -p /tmp/${repo}`)

divide()
info('Copying to the server...')
divide()

await runStreaming(`serverCopy ${processBuildDir}/${params.process}.zip ${domain}:/tmp/${repo}`)

divide()

await runOnServer(domain, `mv /tmp/${repo}/${params.process}.zip $HOME/${repo}/${params.process}`)
await runOnServer(domain, `cd $HOME/${repo}/${params.process} && unzip -o ${params.process}.zip`)
await runOnServer(domain, `cd $HOME/${repo}/${params.process} && npm install --registry="https://mirror-npm.runflare.com" --legacy-peer-deps`)

await runOnServer(domain, `unzip -o $HOME/${repo}/${params.process}/${params.process}.zip -d /tmp/${repo}`)

const user = (await runOnServer(domain, 'whoami', true)).trim()

await runOnServer(
    domain,
    `find /tmp/${repo} -type f -name exports.js -exec sed -i 's|/home/dev/|/home/${user}/|g' {} +`
)

await runOnServer(
    domain,
    `cp -R /tmp/${repo}/node_modules/* $HOME/${repo}/${params.process}/node_modules/`
)

await runOnServer(domain, `rm -rf /tmp/${repo}`)

info('Done')
