#!/usr/bin/env node

import {
    clear,
    runOnTerminal,
    runStreaming,
} from '../scripts/terminal.js'
import {
    divide,
    errorAndExit,
    info,
} from '../scripts/logger.js'
import build from '../scripts/build.js'
import runOnServer from '../scripts/runOnServer.js'
import camelize from '../scripts/camelize.js'

const domain = process.argv[2]
if (!domain) {
    errorAndExit('Domain is not provided')
}

clear()

divide()
info('holism deploy')
divide()

const params = await build({
    isCiCd: false,
    localBuild: true,
})

const {
    isApi,
    isPanel,
    isSite,
    processBuildDir,
    repo,
} = params

await runOnServer(domain, `mkdir -p /tmp/${repo}`)

divide()
info('Copying to the server...')
divide()

await runStreaming(`serverCopy ${processBuildDir}/${params.process}.zip ${domain}:/tmp/${repo}`)

divide()

await runOnServer(domain, `mv /tmp/${repo}/${params.process}.zip $HOME/${repo}/${params.process}`)
await runOnServer(domain, `cd $HOME/${repo}/${params.process} && unzip -o ${params.process}.zip`)
const user = (await runOnServer(domain, 'whoami', true)).trim()

if (isApi) {
    await runOnServer(domain, `cd $HOME/${repo}/${params.process} && npm install --registry='https://mirror-npm.runflare.com' --legacy-peer-deps`)
    await runOnServer(domain, `unzip -o $HOME/${repo}/${params.process}/${params.process}.zip -d /tmp/${repo}`)
    await runOnServer(domain, `find /tmp/${repo} -type f -name exports.js -exec sed -i 's|/home/dev/|/home/${user}/|g' {} +`)
    await runOnServer(domain, `cp -R /tmp/${repo}/node_modules/* $HOME/${repo}/${params.process}/node_modules/`)
}

await runOnServer(domain, `rm -rf /tmp/${repo}`)

const fullProcessName = camelize(`${repo} ${params.process}`)

const port = (await runOnServer(
    domain,
    `grep -oP '127\\.0\\.0\\.1:\\K[0-9]+' $HOME/${repo}/${params.process}/compose.yaml | head -n1`,
    true
)).trim()

if (isApi) {
    await runOnServer(
        domain,
        `ln -s -f $HOME/${repo}/common/connectionStrings.json $HOME/${repo}/${params.process}/connectionStrings.json`
    )
    await runOnServer(
        domain,
        `ln -s -f $HOME/${repo}/common/privateSettings.json $HOME/${repo}/${params.process}/privateSettings.json`
    )
    await runOnServer(
        domain,
        `cd $HOME/${repo}/${params.process} && /usr/local/node/bin/pm2 delete ${fullProcessName} || true && /usr/local/node/bin/pm2 start process.js --name ${fullProcessName} --update-env -- ${port}`
    )
}
else if (isPanel) {
    await runOnServer(
        domain,
        `ln -s -f $HOME/${repo}/common/publicSettings.json $HOME/${repo}/${params.process}/publicSettings.json`
    )
    await runOnServer(domain, `cd $HOME/${repo}/${params.process} && /usr/local/node/bin/pm2 delete ${fullProcessName} || true && /usr/local/node/bin/pm2 start serve --name ${fullProcessName} -- -s . -l ${port}`)
}

info('Done')
