#!/usr/bin/env node

import dnsProviders from '../scripts/dnsProviders.js'
import { runOnTerminal } from '../scripts/terminal.js'
import {
    error,
    info,
    success,
} from '../scripts/logger.js'

const getDnsResolver = () =>
    runOnTerminal(
        `lsof -i :53 | awk 'NR>1 {print $1}' | uniq`
    )

const getCurrentNameServers = () =>
    getDnsResolver() === 'dnsmasq'
        ? runOnTerminal(
            `grep '^server=' /etc/dnsmasq.conf | awk -F '=' '{print $2}'`
        )
        : runOnTerminal(
            `grep '^nameserver' /run/systemd/resolve/resolv.conf | awk '{print $2}'`
        )

const flushDnsCache = () => {
    if (runOnTerminal(`systemctl is-active systemd-resolved`, { hideErrors: true })) {
        runOnTerminal(`sudo systemd-resolve --flush-caches`, { hideErrors: true })
    } else if (runOnTerminal(`command -v resolvectl`, { hideErrors: true })) {
        runOnTerminal(`sudo resolvectl flush-caches`, { hideErrors: true })
    }
}

const listDnsProviders = () => {
    info('Available DNS providers:')
    Object.keys(dnsProviders).forEach(key => info(` ${key}`))
    info(' auto')
}

const showCurrentDns = () => {
    const currentNameServers = getCurrentNameServers()

    const isAuto = currentNameServers
        .split('\n')
        .some(ip =>
            ip.startsWith('192.168.') ||
            ip.startsWith('10.') ||
            ip.match(/^172\.(1[6-9]|2\d|3[0-1])\./)
        )

    if (isAuto) {
        info('DNS is set to DHCP (auto)')
        info('DNS IPs are:')
        info(currentNameServers)
        return
    }

    let matchedKey = ''

    Object.entries(dnsProviders).some(([key, value]) => {
        const [, ips] = value.split('|')

        return ips.split(' ').some(ip => {
            if (currentNameServers.includes(ip)) {
                matchedKey = key
                return true
            }

            return false
        })
    })

    if (matchedKey) {
        const [name] = dnsProviders[matchedKey].split('|')
        info(`Current DNS is ${name}`)
    } else {
        info('Current DNS is unknown')
    }

    info('DNS IPs are:')
    info(currentNameServers)
}

const setAutoDns = () => {
    const dnsResolver = getDnsResolver()

    if (dnsResolver === 'dnsmasq') {
        info('Resetting DNS to DHCP (dnsmasq)')

        runOnTerminal(`sudo sed -i "/^server=/d" /etc/dnsmasq.conf`)
        runOnTerminal(`sudo systemctl restart dnsmasq`)
    } else {
        info('Resetting DNS to DHCP (NetworkManager)')

        const connections = runOnTerminal(
            `nmcli --terse --fields NAME connection show --active | grep -vE '^\\s*$'`
        )
            .split('\n')
            .filter(Boolean)

        connections.forEach(connection => {
            runOnTerminal(`nmcli connection modify "${connection}" ipv4.ignore-auto-dns no`)
            runOnTerminal(`nmcli connection modify "${connection}" ipv4.dns ""`)
            runOnTerminal(`nmcli connection down "${connection}"`)
            runOnTerminal(`nmcli connection up "${connection}"`)
        })
    }

    flushDnsCache()
    success('DNS reset to DHCP defaults')
}

const applyDns = key => {
    if (key === 'auto') {
        setAutoDns()
        return
    }

    if (!dnsProviders[key]) {
        error(`Unknown DNS provider '${key}'`)
        listDnsProviders()
        process.exit(1)
    }

    const [name, ips] = dnsProviders[key].split('|')

    info(`Applying DNS configuration: ${name} (${ips})`)

    const dnsResolver = getDnsResolver()

    if (dnsResolver === 'dnsmasq') {
        const currentConfig = runOnTerminal(
            `grep '^server=' /etc/dnsmasq.conf | awk -F '=' '{print $2}' | tr '\\n' ' '`
        )

        if (currentConfig !== ips) {
            runOnTerminal(`sudo sed -i "/^server=/d" /etc/dnsmasq.conf`)

            ips.split(' ').forEach(ip => {
                runOnTerminal(`echo "server=${ip}" | sudo tee -a /etc/dnsmasq.conf > /dev/null`)
            })

            runOnTerminal(`sudo systemctl restart dnsmasq`)
        }
    } else {
        const connections = runOnTerminal(
            `nmcli --terse --fields NAME connection show --active | grep -vE '^\\s*$'`
        )
            .split('\n')
            .filter(Boolean)

        connections.forEach(connection => {
            runOnTerminal(`nmcli connection modify "${connection}" ipv4.dns "${ips}"`)
            runOnTerminal(`nmcli connection modify "${connection}" ipv4.ignore-auto-dns yes`)
            runOnTerminal(`nmcli connection down "${connection}"`)
            runOnTerminal(`nmcli connection up "${connection}"`)
        })
    }

    flushDnsCache()
    success(`DNS servers updated to ${name} (${ips})`)
}

const nextDnsKey = currentKey => {
    const keys = Object.keys(dnsProviders)
    const index = keys.indexOf(currentKey)

    return index === -1
        ? keys[0]
        : keys[(index + 1) % keys.length]
}

const switchDns = () => {
    const currentDns = getCurrentNameServers()
    let nextKey = ''

    Object.entries(dnsProviders).some(([key, value]) => {
        const [, ips] = value.split('|')
        const firstIp = ips.split(' ')[0]

        if (currentDns.includes(firstIp)) {
            nextKey = nextDnsKey(key)
            return true
        }

        return false
    })

    applyDns(nextKey || Object.keys(dnsProviders)[0])
}

const [arg] = process.argv.slice(2)

if (!arg) {
    showCurrentDns()
} else if (arg === 'list') {
    listDnsProviders()
} else if (arg === 'next') {
    switchDns()
} else {
    applyDns(arg)
}
