#!/usr/bin/env bash

clear

processName=$(basename "$PWD")
if [[ $processName == *Api || $processName == api ]]; then
    cd /$home/$apiRepo
fi

npm install --legacy-peer-deps

# https://runflare.com/mirrors/npm-mirror/
