#!/usr/bin/env node

import findRepos from '../scripts/findRepos.js'
import { runStreaming } from '../scripts/terminal.js'

const gits = findRepos()

if (!gits.length) process.exit(0)

const dirs = gits.join(' ')
await runStreaming(`cloc --fullpath --exclude-dir=node_modules --not-match-d='(^|/)\\.[^/]+' --not-match-f='(^|/)AGENTS\\.md$' ${dirs}`)
