#!/usr/bin/env node

import findRepos from '../scripts/findRepos.js'
import { runStreaming } from '../scripts/terminal.js'

const gits = findRepos()

const dirs = gits.join(' ')
runStreaming(`cloc ${dirs}`, { show: true })
