#!/usr/bin/env node

import { errorAndExit } from '../scripts/logger.js'
import { clear } from '../scripts/terminal.js'
import run from './api/run'

clear()

const tenant = process.argv[2]
if (!tenant) {
    errorAndExit('Tenant is required')
}
if (!/^[a-z][a-zA-Z0-9]*$/.test(tenant)) {
    errorAndExit('Tenant must be a camelCase identifier')
}

if (!process.env.containerHome) {
    errorAndExit('This command must be run inside a container')
}

await run({
    app: 'migration',
    command: 'tenantData',
    show: true,
    tenant,
})
