#!/usr/bin/env bash

workspacePath=/tmp/holism.code-workspace

find "$HOME" -maxdepth 1 -mindepth 1 -type d -exec test -d "{}/.git" \; -print \
    | sort \
    | jq --raw-input --slurp '{ folders: split("\n") | map(select(length > 0) | { path: . }) }' > "$workspacePath"

"$HOME/core/commands/close"
code --new-window "$workspacePath"
