#!/usr/bin/env bash

if sudo grep -q "^$(whoami)" /etc/sudoers; then
    echo "User $(whoami) is already in the sudoers file."
else
    echo "$(whoami) ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers > /dev/null
    echo "User $(whoami) has been added to the sudoers file with all privileges."
fi
