#!/usr/bin/env bash

rm -rf /etc/webServer/conf.d/*
rm -rf /etc/webServer/includes/*
rm -rf ~/webServer/conf.d/*
rm -rf ~/webServer/includes/*

if ! systemctl is-active --quiet nginx; then
    sudo systemctl start nginx
fi

if sudo nginx -t; then
    sudo systemctl restart nginx
else
    echo "Nginx test failed"
fi
