#!/usr/bin/env bash

runnable=$1

. $HOME/core/scripts/logger.sh

if [ -z "$runnable" ]; then
    errorAndExit "Runnable is not provided"
fi

stop $runnable
sudo rm -rf /tmp/$runnable
sudo rm -rf /var/tmp/$runnable

tenantsPath="$HOME/$runnable/common/tenants"

if [ ! -f "$tenantsPath" ]; then
    exit 0
fi

while read -r tenant domain _; do
    domain=${domain%.*}
    find $HOME/webServer -type f -iname "*$domain*" -delete 2>/dev/null
done < "$tenantsPath"
