#!/usr/bin/env bash

processType=$1

. "$HOME/core/scripts/logger.sh"

if [ -z "$processType" ]; then
    errorAndExit "Process type is not provided"
fi

sudo rm -rf "/var/tmp/$processType"

processType=$(echo "$processType" | tr '[:upper:]' '[:lower:]')

pascalCase="$(tr '[:lower:]' '[:upper:]' <<< "${processType:0:1}")${processType:1}"

find /tmp -type d \( \
    -name "*$processType" \
    -o -name "*$pascalCase" \
\) -exec sudo rm -rf {} + 2>/dev/null
