#!/usr/bin/env bash

. $HOME/core/scripts/logger.sh

divide

find "$HOME" -mindepth 2 -maxdepth 2 -type d -name ".git" | while read gitDir; do
  repoDir=$(dirname "$gitDir")
  if [ -f "$repoDir/common/tenants" ]; then
    name=$(basename "$repoDir")
    info "$name"
  fi
done

divide
