#!/usr/bin/env bash

. $HOME/core/scripts/logger.sh

divide

find "$HOME" -type d -name ".git" | while read gitDir; do
  repoDir=$(dirname "$gitDir")
  if [ -d "$repoDir/common" ]; then
    name=$(basename $repoDir)
    if [[ $name == "generation" ]]; then
        continue;
    fi
    info "$name"
  fi
done

divide
