#!/usr/bin/env bash

set -euo pipefail

# https://iran.chabokan.net/
# https://www.arvancloud.ir/fa/dev/linux-repository

homeDir=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)
setupDev="$homeDir/core/setupDev"
scripts="$homeDir/core/scripts"

export homeDir
export setupDev
export scripts

. "$scripts/logger.sh"

gitEmail=$(git config --global --get user.email || true)
gitName=$(git config --global --get user.name || true)

if [[ -z "$gitEmail" ]]; then
    read -rp 'Git email: ' gitEmail
fi

if [[ -z "$gitName" ]]; then
    read -rp 'Git name: ' gitName
fi

export gitEmail
export gitName

clear
divide
info "running setup ..."
divide

$setupDev/setup

node "$homeDir/core/hooks/installHooks.js"
node "$homeDir/core/commands/installCommands.js"
node "$homeDir/core/scripts/setVcsIgnores.js"

. "$scripts/configureHosts.sh"

success "setup complete"
