#!/usr/bin/env bash
set -euo pipefail

# https://iran.chabokan.net/

homeDir=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)
setupDev="$homeDir/core/setupDev"
scripts="$homeDir/core/scripts"

export homeDir
export setupDev
export scripts

. "$scripts/logger.sh"

clear
divide
info "running setup ..."
divide

$setupDev/setup

node "$homeDir/core/hooks/install-hooks.js"
node "$homeDir/core/commands/install-commands.js"
node "$homeDir/core/scripts/setVcsIgnores.js"

. "$scripts/configureHosts.sh"

success "setup complete"
