#!/usr/bin/env node

import {
    errorAndExit,
    divide,
    info,
    warning,
    error,
    getStack,
} from "../scripts/logger.js"
import {
    createDirIfNotExists,
    getFileLines,
    isAccounts,
    isApi,
    isDir,
    isFile,
    isHeadlessPanel,
    isPanel,
    isSite,
    isWorker,
} from "../scripts/os.js"
import {
    clear,
    runOnTerminal,
    runStreaming,
} from "../scripts/terminal.js"
import getPaths from "../scripts/getPaths.js"
import getRandomPort from "../scripts/getRandomPort.js"
import createNetwork from "../scripts/createNetwork.js"
import ensureDependencies from "../scripts/ensureDependencies.js"
import startApi from "../scripts/startApi.js"
import startPanel from "../scripts/startPanel.js"
import startSite from "../scripts/startSite.js"
import processTenantLine from "../scripts/processTenantLine.js"
import extract from "../scripts/extract.js"
import indentation from '../scripts/indentation.js'
import createDirectories from "../scripts/createDirectories.js"
import ensurePathExistsOrCreateIt from "../scripts/ensurePathExistsOrCreateIt.js"

clear()

divide()
info("holism start")
divide()
info(`directory: ${process.cwd()}`)
divide()

let params = extract()
params.isCiCd = process.env.GITHUB_ACTIONS === 'true'

params = {
    ...params,
    ...getPaths(params),
    ...getRandomPort(),
}

const { tenantsPath } = params

if (!isFile(tenantsPath)) {
    errorAndExit(`Tenants file not found at path: ${tenantsPath}`)
}

const lines = getFileLines(tenantsPath)
if (!params.isCiCd) {
    lines.forEach(line => processTenantLine({
        ...params,
        line,
    }))
}

createNetwork(params)
ensureDependencies(params)
params.composeFile = `/tmp/${params.repo}/${params.process}/compose.yaml`
divide()

params.volumes = []
params.addVolume = (left, right) => {
    // if (right.includes('node_modules')) {
    //     error(right, getStack())
    // }
    ensurePathExistsOrCreateIt(left)
    params.volumes.push({ left, right })
}
params.joinVolumes = () => {
    params.volumes.sort((a, b) => a.left.localeCompare(b.left))
    params.volumes = '\n' + params.volumes
        .map(volume => `${indentation}- ${volume.left}:${volume.right}`)
        .join('\n')
}

if (isAccounts(params)) {
    startAccounts(params)
} else if (isApi(params)) {
    startApi(params)
} else if (isPanel(params)) {
    if (isHeadlessPanel(params)) {
        startHeadlessPanel(params)
    } else {
        startPanel(params)
    }
} else if (isSite(params)) {
    startSite(params)
} else if (isWorker(params)) {
    startNodeApi(params)
} else {
    warning('Unknown process')
}

let command = `docker compose -p ${params.lowercaseRepo}-${params.lowercaseProcess} -f ${params.composeFile} up --remove-orphans -d`
// console.log(command)
runOnTerminal(command)
command = `docker compose -p ${params.lowercaseRepo}-${params.lowercaseProcess} -f ${params.composeFile} logs -f`
if (params.isCiCd) {
    runOnTerminal(command)
}
else {
    await runStreaming(command)
}
