#!/usr/bin/env node

import fs from "fs"
import path from "path"
import process from "process"
import { execSync } from "child_process"
import {
    errorAndExit,
    divide,
    info,
    success,
} from "../logger.js"
import {
    exit,
    getDepth,
    getOrgRepoFromGit,
} from "../scripts/os"
import { clear } from "../scripts/terminal"
import setPaths from "../scripts/setPaths.js"

clear()

const cwd = process.cwd()
if (cwd === "/") {
    errorAndExit("Can not run `start` from the root directory")
}
if (cwd === process.env.HOME) {
    errorAndExit("Can not run `start` from the home directory")
}

const {
    org,
    repo,
} = getOrgRepoFromGit()

if (org?.toLowerCase() === "gesht") {
    errorAndExit("Start command is not available for gesht repos. They are not executable/runnable. Run `start` command from a runnable project.")
}

if (org[0] !== org[0].toLowerCase())
    errorAndExit("Invalid Organization. Organization name should start with a lowercase letter.")

if (getDepth() !== 4) {
    errorAndExit("Start should only be run from inside a process (API, panel, site, worker, etc.)")
}

divide()
info("gesht start")
divide()
info(`directory: ${cwd}`)
divide()

const processName = path.basename(cwd)

const lowercaseOrg = org.toLowerCase()
const lowercaseRepo = repo.toLowerCase()
const lowercaseProcess = processName.toLowerCase()

process.env.org = org
process.env.repo = repo
process.env.process = processName
process.env.lowercaseOrg = lowercaseOrg
process.env.lowercaseRepo = lowercaseRepo
process.env.lowercaseProcess = lowercaseProcess

success(`organization: ${org}`)
success(`repository: ${repo}`)
success(`process: ${process}`)

setPaths()

divide()


