#!/usr/bin/env bash

echo
homeDir=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)
. "$homeDir/core/scripts/logger.sh"

clear

divide
info "Stopping all ..."
divide

pattern="${1:-}"

docker ps -a -q | while read -r i
do
    containerName=$(docker inspect "$i" | grep 'Name.*/' | grep -v = | cut -d'/' -f2 | cut -d'"' -f1)

    if [[ -z "$pattern" ]] || echo "$containerName" | grep -iq "$pattern"; then
        docker rm "$i" --force 1>/dev/null
        check "$containerName"
    fi
done

docker system prune --force 1>/dev/null

divide
success "Stopped all"
divide
