#!/usr/bin/env bash

set -e

base=$home/$repo/$process
for dir in $base/src/parts/*; do
    [ -d "$dir" ] || continue
    topLevelDir=$(basename "$dir")
    node $home/core/commands/site/generateExports.js "$topLevelDir" parts
    node $home/core/commands/site/createPartItemBarrels.js "$topLevelDir"
done
for dir in $base/src/pageParts/*; do
    [ -d "$dir" ] || continue
    topLevelDir=$(basename "$dir")
    [ "$topLevelDir" = "sharedFallbacks" ] && continue
    node $home/core/commands/site/generateExports.js "$topLevelDir" pageParts
done
node $home/site/loaderProvider.js
node --input-type=module -e "import('$home/site/emptyDashboardProvider.js').then(({ default: provide }) => provide([]))"
node $home/core/commands/site/initializeSiteBarrels.js
