#!/usr/bin/env bash

for dir in /$repo/$process/src/parts/*; do
    [ -d "$dir" ] || continue
    topLevelDir=$(basename "$dir")
    node /core/commands/site/generateExports.js "$topLevelDir" parts
done
for dir in /$repo/$process/src/pageParts/*; do
    [ -d "$dir" ] || continue
    topLevelDir=$(basename "$dir")
    node /core/commands/site/generateExports.js "$topLevelDir" pageParts
done

node /core/commands/site/initializeSiteBarrels.js

inotifywait -m -r \
-e modify \
-e move \
-e create \
-e delete \
--exclude "exports.js" \
-q \
/$repo/$process/src/pageParts |
while IFS=' ' read directory event file
do
    export directory
    export event
    export file
    # echo $directory $file $event
    topLevelDir=$(echo "$directory" | cut -d'/' -f1)
    node /core/commands/site/generateExports.js "$topLevelDir" parts
    node /core/commands/site/initializeSiteBarrels.js
done
