#!/usr/bin/env bash

base=$home/$repo/$process
for dir in $base/src/parts/*; do
    [ -d "$dir" ] || continue
    topLevelDir=$(basename "$dir")
    node $home/core/commands/site/generateExports.js "$topLevelDir" parts
done
for dir in $base/src/pageParts/*; do
    [ -d "$dir" ] || continue
    topLevelDir=$(basename "$dir")
    node $home/core/commands/site/generateExports.js "$topLevelDir" pageParts
done

node $home/core/commands/site/initializeSiteBarrels.js

inotifywait -m -r \
-e modify \
-e move \
-e create \
-e delete \
--exclude "exports.js" \
-q \
$base/src/pageParts |
while IFS=' ' read directory event file
do
    export directory
    export event
    export file
    echo $directory $file $event
    topLevelDir=$(echo "$directory" | cut -d'/' -f1)
    if [[ "$directory" == *"/pageParts/"* ]]; then
        target=pageParts
    else
        target=parts
    fi
    node $home/core/commands/site/generateExports.js "$topLevelDir" "$target"
    node $home/core/commands/site/initializeSiteBarrels.js
done
