export default {
    en: { name: 'English', speakers: 1500 },
    zh: { name: 'Mandarin Chinese', speakers: 1184 },
    hi: { name: 'Hindi', speakers: 609 },
    es: { name: 'Spanish', speakers: 558 },
    ar: { name: 'Arabic', speakers: 335 },
    fr: { name: 'French', speakers: 312 },
    bn: { name: 'Bengali', speakers: 284 },
    pt: { name: 'Portuguese', speakers: 267 },
    ru: { name: 'Russian', speakers: 253 },
    id: { name: 'Indonesian', speakers: 252 },
    ur: { name: 'Urdu', speakers: 246 },
    de: { name: 'German', speakers: 134 },
    ja: { name: 'Japanese', speakers: 126 },
    arz: { name: 'Egyptian Arabic', speakers: 119 },
    mr: { name: 'Marathi', speakers: 99 },
    vi: { name: 'Vietnamese', speakers: 97 },
    te: { name: 'Telugu', speakers: 96 },
    ha: { name: 'Hausa', speakers: 94 },
    tr: { name: 'Turkish', speakers: 91 },
    pa: { name: 'Punjabi', speakers: 90 },
    sw: { name: 'Swahili', speakers: 87 },
    fil: { name: 'Filipino', speakers: 87 },
    ta: { name: 'Tamil', speakers: 86 },
    yue: { name: 'Cantonese', speakers: 86 },
    wuu: { name: 'Wu Chinese', speakers: 83 },
    fa: { name: 'Persian', speakers: 83 },
    ko: { name: 'Korean', speakers: 82 },
    th: { name: 'Thai', speakers: 71 },
    jv: { name: 'Javanese', speakers: 69 },
    it: { name: 'Italian', speakers: 66 },
    gu: { name: 'Gujarati', speakers: 62 },
    apc: { name: 'Levantine Arabic', speakers: 60 },
    am: { name: 'Amharic', speakers: 60 },
    kn: { name: 'Kannada', speakers: 59 },
    bho: { name: 'Bhojpuri', speakers: 53 },
    apd: { name: 'Sudanese Arabic', speakers: 52 },
    om: { name: 'Oromo', speakers: 47 },
    yo: { name: 'Yoruba', speakers: 45 },
    ig: { name: 'Igbo', speakers: 44 },
    az: { name: 'Azerbaijani', speakers: 41 },
    ms: { name: 'Malay', speakers: 41 },
    uz: { name: 'Uzbek', speakers: 40 },
    sd: { name: 'Sindhi', speakers: 39 },
    si: { name: 'Sinhala', speakers: 37 },
    km: { name: 'Khmer', speakers: 36 },
    mg: { name: 'Malagasy', speakers: 35 },
    ne: { name: 'Nepali', speakers: 35 },
    my: { name: 'Burmese', speakers: 33 },
    ht: { name: 'Haitian Creole', speakers: 30 },
    nl: { name: 'Dutch', speakers: 30 },
    pl: { name: 'Polish', speakers: null },
    ro: { name: 'Romanian', speakers: null },
    uk: { name: 'Ukrainian', speakers: null },
    el: { name: 'Greek', speakers: null },
    sv: { name: 'Swedish', speakers: null },
    cs: { name: 'Czech', speakers: null },
    ca: { name: 'Catalan', speakers: null },
    sr: { name: 'Serbian', speakers: null },
    hu: { name: 'Hungarian', speakers: null },
    bg: { name: 'Bulgarian', speakers: null },
    he: { name: 'Hebrew', speakers: null },
    da: { name: 'Danish', speakers: null },
    fi: { name: 'Finnish', speakers: null },
    hr: { name: 'Croatian', speakers: null },
    nb: { name: 'Norwegian Bokmål', speakers: null },
    sk: { name: 'Slovak', speakers: null },
    lt: { name: 'Lithuanian', speakers: null },
    sl: { name: 'Slovenian', speakers: null },
    lv: { name: 'Latvian', speakers: null },
    et: { name: 'Estonian', speakers: null },
    af: { name: 'Afrikaans', speakers: null },
    ml: { name: 'Malayalam', speakers: null }
}
