#!/usr/bin/env node

import createControlPanelFiles from '../../scripts/createControlPanelFiles.js'
import isControlPanel from '../../scripts/isControlPanel.js'
import { info } from '../../scripts/logger.js'
import { runOnTerminal } from '../../scripts/terminal.js'

const {
    home,
    isCiCd,
    process: proc,
    processPath,
    repo,
} = process.env

const main = () => {
    process.chdir(`${home}/${repo}/${proc}`)
    if (isControlPanel({
        process: proc,
        repo,
    })) {
        createControlPanelFiles(processPath)
    }
    runOnTerminal('merge panel', {
        show: true,
        throwOnError: true,
    })
    runOnTerminal('initialize', {
        show: true,
        throwOnError: true,
    })
    if (isCiCd !== 'true') {
        runOnTerminal('install', {
            show: true,
            throwOnError: true,
        })
    }
    runOnTerminal('touch /tmp/panelReady', {
        show: true,
        throwOnError: true,
    })
}

try {
    main()
}
catch (e) {
    info(String(e))
    process.exitCode = 1
}
