#!/usr/bin/env bash

. "$scripts/installer.sh"

install_anydesk() {
    sudo rm -f /etc/apt/sources.list.d/anydesk-stable.list
    sudo rm -f /etc/apt/sources.list.d/anydesk.list
    sudo rm -f /usr/share/keyrings/anydesk.gpg
    sudo rm -f /usr/share/keyrings/anydesk-archive-keyring.gpg
    curl -fsSL https://keys.anydesk.com/repos/DEB-GPG-KEY | gpg --dearmor | sudo tee /usr/share/keyrings/anydesk-archive-keyring.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/anydesk-archive-keyring.gpg] http://deb.anydesk.com/ all main" | sudo tee /etc/apt/sources.list.d/anydesk.list > /dev/null
    sudo apt-get -o Acquire::ForceIPv4=true update
    sudo apt-get install -y anydesk
}

install anydesk install_anydesk
