#!/usr/bin/env bash

set -euo pipefail

loadState=$(systemctl --user show astCstWatcher.service --property=LoadState --value)

if [[ "$loadState" != 'not-found' ]]; then
    systemctl --user disable --now astCstWatcher.service
fi
