#!/usr/bin/env bash

. "$scripts/installer.sh"

install_bash_completion() {
    grep -wq '^source /etc/profile.d/bash_completion.sh' ~/.bashrc || echo 'source /etc/profile.d/bash_completion.sh' >> ~/.bashrc
    source /etc/profile.d/bash_completion.sh
    if [ -f /etc/profile.d/bash_completion.sh ]; then
        return
    fi
    sudo apt install bash-completion -y
}

install bash-completion install_bash_completion
