#!/usr/bin/env bash

. "$scripts/installer.sh"

install_bcompare() {
    wget https://www.scootersoftware.com/files/bcompare-4.4.7.28397_amd64.deb
    sudo apt-get install -y ./bcompare-4.4.7.28397_amd64.deb
}

install bcompare install_bcompare
