#!/usr/bin/env bash

. "$scripts/installer.sh"

install_google_chrome() {
    curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo tee /usr/share/keyrings/google-chrome.gpg > /dev/null
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable
}

install google-chrome install_google_chrome
