#!/usr/bin/env bash

git config --global init.defaultBranch main
git config --global core.filemode true
git config --global user.signingkey ~/.ssh/id_ed25519
git config --global commit.gpgsign true
git config --global gpg.format ssh