#!/usr/bin/env bash

set -euo pipefail

sudo mkdir -p /etc/gdm3

sudo grep -q '^WaylandEnable=' /etc/gdm3/custom.conf \
    && sudo sed -i 's/^WaylandEnable=.*/WaylandEnable=false/' /etc/gdm3/custom.conf \
    || echo 'WaylandEnable=false' | sudo tee -a /etc/gdm3/custom.conf > /dev/null

sudo grep -q '^AutomaticLoginEnable=' /etc/gdm3/custom.conf \
    && sudo sed -i 's/^AutomaticLoginEnable=.*/AutomaticLoginEnable=true/' /etc/gdm3/custom.conf \
    || echo 'AutomaticLoginEnable=true' | sudo tee -a /etc/gdm3/custom.conf > /dev/null

sudo grep -q '^AutomaticLogin=' /etc/gdm3/custom.conf \
    && sudo sed -i "s/^AutomaticLogin=.*/AutomaticLogin=$USER/" /etc/gdm3/custom.conf \
    || echo "AutomaticLogin=$USER" | sudo tee -a /etc/gdm3/custom.conf > /dev/null
