#!/usr/bin/env bash

set -euo pipefail

sudo sed -i 's/#\s*WaylandEnable\s*=.*$/WaylandEnable=false/g' /etc/gdm3/custom.conf
sudo sed -i 's/#\s*AutomaticLoginEnable\s*=.*$/AutomaticLoginEnable=true/g' /etc/gdm3/custom.conf
sudo sed -i "s/#\s*AutomaticLogin\s*=.*$/AutomaticLogin=$USER/g" /etc/gdm3/custom.conf