#!/usr/bin/env bash

. "$scripts/installer.sh"

installDnsmasq() {
    sudo apt install dnsmasq -y
    sudo systemctl stop systemd-resolved
    sudo systemctl disable systemd-resolved
    sudo systemctl restart dnsmasq
}

install dnsmasq installDnsmasq
