#!/usr/bin/env bash

. "$scripts/installer.sh"

install_docker_compose() {
    sudo apt-get update -y
    sudo apt-get install -y docker-compose-plugin
}

install docker-compose install_docker_compose
