#!/usr/bin/env bash

set -euo pipefail

sshKeyPath="$homeDir/.ssh/id_ed25519"

if [[ -f "$sshKeyPath" ]]; then
    exit 0
fi

mkdir -p "$homeDir/.ssh"
chassis=$($setupDev/getChassis)
ssh-keygen -t ed25519 -C "$chassis $gitEmail" -f "$sshKeyPath" -N ''
