#!/usr/bin/env bash

set -euo pipefail

sudo sysctl fs.inotify.max_user_instances=8192 >/dev/null

sudo sed -i 's/^.*DefaultLimitNOFILE=.*$/DefaultLimitNOFILE=65536/g' /etc/systemd/system.conf
sudo sed -i 's/^.*DefaultLimitNOFILE=.*$/DefaultLimitNOFILE=65536/g' /etc/systemd/user.conf