#!/usr/bin/env bash
. "$scripts/installer.sh"
. "$scripts/logger.sh"

installNode() {
    sudo apt-get update -y
    sudo apt-get install -y curl ca-certificates gnupg jq
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    echo 'export NODE_OPTIONS="--trace-deprecation"' >> ~/.bashrc
    export NODE_OPTIONS="--trace-deprecation"
}

latestLts=$(curl -s https://nodejs.org/dist/index.json | jq -r '[.[] | select(.lts != false)][0].version')

installedMajor=$(node --version)

if [[ "$installedMajor" == "$latestLts" ]]; then
    success "Node.js $checkMark"
else
    install node installNode
fi
