#!/usr/bin/env bash

. "$scripts/installer.sh"

install_postgres() {
    sudo apt-get update -y
    sudo apt-get install -y postgresql postgresql-contrib
    sudo systemctl enable postgresql
}

install postgres install_postgres
