#!/usr/bin/env bash

. "$scripts/installer.sh"

installPython() {
    sudo apt-get update -y
    sudo apt-get install -y python3 python3-pip python3-venv
    python3 --version
    pip3 --version
}

install python installPython
