#!/usr/bin/env bash

. "$scripts/installer.sh"

install_redis() {
    sudo apt-get update -y
    sudo apt-get install -y redis-server
    sudo systemctl enable redis-server
}

install redis install_redis
