#!/usr/bin/env bash

. "$scripts/installer.sh"

installSafeEyes() {
    sudo add-apt-repository ppa:safeeyes-team/safeeyes -y
    sudo apt-get update
    sudo apt-get install safeeyes -y
}

install safeeyes installSafeEyes
