#!/usr/bin/env bash

. "$scripts/installer.sh"

install_safeeyes() {
    sudo add-apt-repository ppa:safeeyes-team/safeeyes -y
    sudo apt-get update
    sudo apt-get install safeeyes -y
}

install safeeyes install_safeeyes
