#!/usr/bin/env bash

set -euo pipefail

gsettings set org.gnome.shell favorite-apps "[
  'org.gnome.Nautilus.desktop',
  'google-chrome.desktop',
  'code.desktop',
  'org.gnome.Ptyxis.desktop',
  'org.gnome.gedit.desktop'
]"
