#!/usr/bin/env bash
set -euo pipefail

. "$scripts/installer.sh"

runSetupStep astCstWatcher "$setupDev/astCstWatcher"

runSetupStep protectSecrets "$setupDev/protectSecrets"

runSetupStep curl install curl
runSetupStep jq install jq
runSetupStep nmap install nmap
runSetupStep cloc install cloc
runSetupStep parallel install parallel
runSetupStep progress install progress
runSetupStep rename install rename
runSetupStep baobab install baobab
runSetupStep dconfEditor install dconf-editor
runSetupStep nginx install nginx
runSetupStep kooha install kooha
runSetupStep sshd install sshd openssh-server
runSetupStep telnet install telnet
runSetupStep unzip install unzip
runSetupStep zip install zip
runSetupStep http install http httpie
runSetupStep pip install pip python3-pip

runSetupStep git "$setupDev/git"
runSetupStep gh "$setupDev/gh"
runSetupStep chrome "$setupDev/chrome"
runSetupStep vsCode "$setupDev/vsCode"
# $setupDev/spellChecker
runSetupStep speedTest "$setupDev/speedTest"
# $setupDev/remoteContainers

runSetupStep docker "$setupDev/docker"
runSetupStep platformStartup "$setupDev/platformStartup"
runSetupStep node "$setupDev/node"
runSetupStep coreDependencies "$setupDev/coreDependencies"
runSetupStep mongodbMemoryServer "$setupDev/mongodbMemoryServer"
runSetupStep nginxConfiguration sudo homeDir="$homeDir" node "$setupDev/nginx"

runSetupStep micro "$setupDev/micro"
runSetupStep mkcert "$setupDev/mkcert"
runSetupStep rclone "$setupDev/rclone"
runSetupStep azureCli "$setupDev/azureCli"

runSetupStep anyDesk "$setupDev/anyDesk"
runSetupStep rustDesk "$setupDev/rustDesk"
runSetupStep compass "$setupDev/compass"
runSetupStep beyondCompare "$setupDev/beyondCompare"
runSetupStep safeEyes "$setupDev/safeEyes"

# $setupDev/dnsmasq
# $setupDev/stretchly
# $setupDev/warpCli
# $setupDev/bashCompletion
# bash "$(dirname "$0")/npmPackages"
# bash "$(dirname "$0")/adsPower"
# bash "$(dirname "$0")/astrill"

runSetupStep configureApt "$setupDev/configureApt"
runSetupStep giveAccessToRoot "$setupDev/giveAccessToRoot"
runSetupStep addPersianInputSource "$setupDev/addPersianInputSource"
runSetupStep setLocaleToEnglishUs "$setupDev/setLocaleToEnglishUs"
runSetupStep configureKeyboard "$setupDev/configureKeyboard"
runSetupStep setFavoriteApps "$setupDev/setFavoriteApps"
runSetupStep setChromeAsDefaultBrowser "$setupDev/setChromeAsDefaultBrowser"
runSetupStep disableWayland "$setupDev/disableWayland"
runSetupStep setAppsToOpenMaximized "$setupDev/setAppsToOpenMaximized"
runSetupStep preventDockAutoHide "$setupDev/preventDockAutoHide"
runSetupStep increaseLimits "$setupDev/increaseLimits"
runSetupStep preventDimmingAndSleeping "$setupDev/preventDimmingAndSleeping"
runSetupStep preventMultipleWorkspaces "$setupDev/preventMultipleWorkspaces"
runSetupStep disableAutomaticScreenLock "$setupDev/disableAutomaticScreenLock"
runSetupStep setCalculatorThousandsSeparator "$setupDev/setCalculatorThousandsSeparator"
runSetupStep setTimeZone "$setupDev/setTimeZone"
runSetupStep generateSshKey "$setupDev/generateSshKey"
runSetupStep configureGitHub "$setupDev/configureGitHub"
runSetupStep configureGit "$setupDev/configureGit"
runSetupStep enableDnd "$setupDev/enableDnd"
runSetupStep configureDockerForUser "$setupDev/configureDockerForUser"
runSetupStep setInstallationDate "$setupDev/setInstallationDate"
runSetupStep removeProblematicSources "$setupDev/removeProblematicSources"
runSetupStep disableInertialScrolling "$setupDev/disableInertialScrolling"

if (( setupFailures > 0 )); then
    exit 1
fi
