#!/usr/bin/env bash

. "$scripts/installer.sh"

installSpeedTest() {
    sudo apt-get install -y gnupg1 apt-transport-https dirmngr
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
    sudo sed -i 's/resolute/jammy/g' /etc/apt/sources.list.d/ookla_speedtest-cli.list
    sudo apt-get update -y
    sudo apt-get install -y speedtest
}

install speedtest installSpeedTest
