#!/usr/bin/env bash

. "$scripts/installer.sh"

installSpeedTest() {
    sudo apt-get install gnupg1 apt-transport-https dirmngr
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
    sudo apt-get install speedtest
}

install speedtest installSpeedTest
