#!/usr/bin/env bash

. "$scripts/installer.sh"

install_vscode_code_spell_checker() {
    if code --list-extensions | grep -q 'streetsidesoftware.code-spell-checker'; then
        timeout 50s code --install-extension streetsidesoftware.code-spell-checker --force 2>&1 >/dev/null || return
        return
    fi
    timeout 50s code --install-extension streetsidesoftware.code-spell-checker
}

install vscode-code-spell-checker install_vscode_code_spell_checker
