name: api

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
  push:
    branches:
      - main
    paths:
      - 'container/files/dev/api'

jobs:
  build-api:
    uses: ./.github/workflows/builder.yaml
    with:
      service: api
    secrets: inherit
