name: apiProdBase

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
  push:
    branches:
      - main
    paths:
      - 'container/files/prod/apiProdBase'

jobs:
  build:
    uses: ./.github/workflows/builder.yaml
    with:
      service: apiProdBase
      dir: prod
    secrets: inherit
