name: builder

on:
    workflow_call:
        inputs:
            file:
                required: true
                type: string
            dir:
                type: string
                default: dev
            tag:
                required: false
                type: string

env:
    GH_TOKEN: ${{ secrets.PAT }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Initialize
              if: startsWith(runner.name, 'GitHub')
              run: |
                  echo "~/core/commands" >> $GITHUB_PATH
                  mkdir ~/secrets
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH }}" > ~/.ssh/id_ed25519
                  chmod --preserve-root 400 ~/.ssh/id_ed25519
                  cd ~
                  git clone git@github.com:holizm/core
                  git clone git@github.com:holizm/phoneCode

            - name: Log in to Docker Hub
              run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build Docker image
              run: |
                  image="${{ secrets.DOCKER_USERNAME }}/${{ inputs.tag || inputs.file }}:latest"

                  docker --debug build \
                      -f "$HOME/core/container/files/${{ inputs.dir }}/${{ inputs.file }}" \
                      -t "$image" \
                      "$HOME" \
                      --no-cache \
                      --progress=plain

            - name: Push Docker image
              run: |
                  image="${{ secrets.DOCKER_USERNAME }}/${{ inputs.tag || inputs.file }}:latest"

                  docker push "$image"                  

            - name: Log out from Docker Hub
              run: docker logout
