name: core

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
  push:
    branches:
      - main
    paths:
      - 'container/files/dev/core'

jobs:
  build-core:
    uses: ./.github/workflows/builder.yaml
    with:
      service: core
    secrets: inherit
